name: wp-demo

networks:
  wp-demo:
    driver: bridge

volumes:
  wp-db:

services:
  wp-db:
    image: mysql:8.0
    container_name: wp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - wp-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp-demo

  wp-app:
    build: .
    container_name: wp-app
    restart: unless-stopped
    depends_on:
      - wp-db
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin
    networks:
      - wp-demo


