name: wp-demo

networks:
  wp-demo:
    driver: bridge

volumes:
  wp-db:

services:
  wp-db:
    image: mysql:8.0
    container_name: wp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - wp-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp-demo

  wp-app:
    build: .
    container_name: wp-app
    restart: unless-stopped
    depends_on:
      - wp-db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin
    networks:
      - wp-demo

  seeder:
    container_name: seeder
    build:
      context: ./k6
      dockerfile: Dockerfile
    environment:
      K6_SCRIPT: database-seeder.js
      SEED_CATEGORIES_TOTAL: 1
      SEED_PRODUCTS_TOTAL: 5
      SEED_ORDERS_TOTAL: 5
      BATCH_SIZE: 3
      WOO_API_ENDPOINT: "http://wp-app:80/wp-json/wc/v3"
      MAX_DURATION: "300s"
      VERBOSE: true
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 128M
    restart: "no"
    networks:
      - wp-demo

